### ISSUE TITLE
NeoForge?

### ISSUE THREAD

**Issue by Rusmer** [sylvxa/noglow#1]
Will there be support for Forge/NeoForge?

**Comment by sylvxa** [comment]
hey there! there are no set plans for a forge port at a moment but i may look into it later when i have time. i've never developed for forge so it's a little out of scope right now.

**Comment by Rusmer** [comment]
I found a mod on neoforge to run mods with fabric
If anyone needs it, here it is: https://modrinth.com/mod/connector
