### ISSUE TITLE
Issues when launched

### ISSUE THREAD

**Issue by Mopped87** [sylvxa/noglow#3]
When I launch the game it kicks me back to the launcher because it says there were issues with the mod “no glow” exit code -1. How do I fix it?

**Comment by sylvxa** [comment]
Hi there! Do you think you could get me a more detailed crash log? Find your `%appdata/.minecraft/logs/latest.log` (or wherever your minecraft folder is) and post it on mclo.gs, then reply with that.

**Comment by Mopped87** [comment]
I fixed it all I had to do was delete the Minecraft folder then create another to put the mod in
